#changeLogFile=src/main/resources/db/changelog/root.yaml
changeLogFile=src/main/resources/db/changelog/second-root.yaml

# target (Database):
url=jdbc:postgresql://localhost:5432/demo1
#liquibase.command.defaultSchemaName=public
username=postgres
password=postgres
driver=org.postgresql.Driver
#liquibase.command.defaultSchemaName=public
#liquibase.command.schemas=public

# source of truth (a package with JPA Entities):
referenceUrl=hibernate:my.example.demoliqgr.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver

# source of truth (if comparing with another database):
#referenceUrl=jdbc:postgresql://localhost:5432/demo2
#liquibase.command.referenceDefaultSchemaName=public
#referenceUsername=postgres
#referencePassword=postgres
#referenceDriver=org.postgresql.Driver